/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagement;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aswin
 */
public class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form Rooms
     */
    public Rooms() {
        initComponents();
        fetch();
        clear();
        jScrollPane1.getViewport().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type = new javax.swing.ButtonGroup();
        category = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RRoomNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        single = new javax.swing.JRadioButton();
        doub = new javax.swing.JRadioButton();
        family = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        ac = new javax.swing.JRadioButton();
        non = new javax.swing.JRadioButton();
        RAdd = new javax.swing.JButton();
        RUpdate = new javax.swing.JButton();
        RDelete = new javax.swing.JButton();
        RNext = new javax.swing.JButton();
        RHome = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Room No :");

        RRoomNo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        RRoomNo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Category :");

        category.add(single);
        single.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        single.setText("Single");

        category.add(doub);
        doub.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        doub.setText("Double");

        category.add(family);
        family.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        family.setText("Family");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("Type :");

        type.add(ac);
        ac.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        ac.setText("AC");

        type.add(non);
        non.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        non.setText("NON-AC");

        RAdd.setBackground(new java.awt.Color(204, 233, 255));
        RAdd.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        RAdd.setForeground(new java.awt.Color(51, 0, 51));
        RAdd.setText("ADD");
        RAdd.setPreferredSize(new java.awt.Dimension(82, 22));
        RAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAddActionPerformed(evt);
            }
        });

        RUpdate.setBackground(new java.awt.Color(204, 233, 255));
        RUpdate.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        RUpdate.setForeground(new java.awt.Color(51, 0, 51));
        RUpdate.setText("UPDATE");
        RUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUpdateActionPerformed(evt);
            }
        });

        RDelete.setBackground(new java.awt.Color(204, 233, 255));
        RDelete.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        RDelete.setForeground(new java.awt.Color(51, 0, 51));
        RDelete.setText("DELETE");
        RDelete.setPreferredSize(new java.awt.Dimension(82, 22));
        RDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDeleteActionPerformed(evt);
            }
        });

        RNext.setBackground(new java.awt.Color(204, 233, 255));
        RNext.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        RNext.setForeground(new java.awt.Color(51, 0, 51));
        RNext.setText("RATE");
        RNext.setPreferredSize(new java.awt.Dimension(82, 22));
        RNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RNextActionPerformed(evt);
            }
        });

        RHome.setBackground(new java.awt.Color(204, 233, 255));
        RHome.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        RHome.setForeground(new java.awt.Color(51, 0, 51));
        RHome.setText("HOME");
        RHome.setPreferredSize(new java.awt.Dimension(82, 22));
        RHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RHomeActionPerformed(evt);
            }
        });

        RoomTable.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        RoomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Room No", "Category", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        RoomTable.setRowHeight(22);
        RoomTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(RoomTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(family)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ac)
                                .addGap(18, 18, 18)
                                .addComponent(non))
                            .addComponent(single)
                            .addComponent(jSeparator1)
                            .addComponent(RRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doub))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RHome, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RNext, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RNext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(single))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doub)
                        .addGap(18, 18, 18)
                        .addComponent(family)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ac)
                        .addComponent(non)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 750, 730));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/rooms.png"))); // NOI18N
        jLabel4.setRequestFocusEnabled(false);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUpdateActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel d1=(DefaultTableModel)RoomTable.getModel();
            int index=Integer.parseInt(d1.getValueAt(RoomTable.getSelectedRow(),0).toString());
            String RoomNo=RRoomNo.getText();
            String Category;
            if(single.isSelected()){
                Category="Single";
            }
            else if(doub.isSelected()){
                Category="Double";
            }
            else{
                Category="Family Cot";
            }
            String Type;
            if(ac.isSelected()){
                Type="AC";
            }
            else{
                Type="NON-AC";
            }

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/HotelManagement","root","");
            String sql="update Rooms set Room='"+RoomNo+"',Type='"+Type+"',Category='"+Category+"' where ID='"+index+"'";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.executeUpdate(sql);
            fetch();
            clear();
            JOptionPane.showMessageDialog(null, "Updated");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_RUpdateActionPerformed

    private void RDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDeleteActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel d1=(DefaultTableModel)RoomTable.getModel();
            int index=Integer.parseInt(d1.getValueAt(RoomTable.getSelectedRow(),0).toString());
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/HotelManagement","root","");
            String sql="DELETE FROM Rooms WHERE ID='"+index+"'";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.executeUpdate(sql);
            fetch();
            clear();
            JOptionPane.showMessageDialog(null, "Deleted");
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_RDeleteActionPerformed

    private void RAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAddActionPerformed
        // TODO add your handling code here:

        try{
            String RoomNo=RRoomNo.getText();
            String Category;
            if(single.isSelected()){
                Category="Single";
            }
            else if(doub.isSelected()){
                Category="Double";
            }
            else{
                Category="Family";
            }
            String Type;
            if(ac.isSelected()){
                Type="AC";
            }
            else{
                Type="NON-AC";
            }
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/HotelManagement","root","");
            String sql="INSERT INTO Rooms(Room,Type,Category)VALUES('"+RoomNo+"','"+Type+"','"+Category+"');";
            Statement st=con.createStatement();
            int rs=st.executeUpdate(sql);
            if(rs==1){
                JOptionPane.showMessageDialog(this,"Data Added");
                fetch();
                clear();
            }

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_RAddActionPerformed

    private void RNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RNextActionPerformed
        // TODO add your handling code here:
        Amount am=new Amount();
        am.show();
        dispose();
    }//GEN-LAST:event_RNextActionPerformed

    private void RHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RHomeActionPerformed
        // TODO add your handling code here:
        Dashboard d=new Dashboard();
        d.show();
        dispose();
    }//GEN-LAST:event_RHomeActionPerformed

    private void RoomTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1=(DefaultTableModel)RoomTable.getModel();
        int index=RoomTable.getSelectedRow();
        RRoomNo.setText(d1.getValueAt(index, 1).toString());
        if(d1.getValueAt(index,2).toString().equals("Single")){
            single.setSelected(true);
        }else if(d1.getValueAt(index,2).toString().equals("Double")){
            doub.setSelected(true);
        }else{
            family.setSelected(true);
        }
        if(d1.getValueAt(index,3).toString().equals("AC")){
            ac.setSelected(true);
        }
        else{
            non.setSelected(true);
        }
    }//GEN-LAST:event_RoomTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RAdd;
    private javax.swing.JButton RDelete;
    private javax.swing.JButton RHome;
    private javax.swing.JButton RNext;
    private javax.swing.JTextField RRoomNo;
    private javax.swing.JButton RUpdate;
    private javax.swing.JTable RoomTable;
    private javax.swing.JRadioButton ac;
    private javax.swing.ButtonGroup category;
    private javax.swing.JRadioButton doub;
    private javax.swing.JRadioButton family;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton non;
    private javax.swing.JRadioButton single;
    private javax.swing.ButtonGroup type;
    // End of variables declaration//GEN-END:variables

    
    private void fetch() {
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/HotelManagement","root","");
           String sql="select * from Rooms";
           Statement stmt=con.createStatement();
           ResultSet rs=stmt.executeQuery(sql);
           DefaultTableModel d1=(DefaultTableModel)RoomTable.getModel();
           d1.setRowCount(0);
           while(rs.next())
           {
               
               Vector v2=new Vector();
                    v2.add(rs.getString("ID"));
                    v2.add(rs.getString("Room"));
                    v2.add(rs.getString("Category"));
                    v2.add(rs.getString("Type"));
               d1.addRow(v2);
           }
       }
       catch(Exception e)
       {
           System.out.println(e);
       }
    }
    private void clear() {
        RRoomNo.setText("");
        this.category.clearSelection();
        this.type.clearSelection();
    }
}
